// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kinde.Api.Kiota.Management.Api.V1.Connections.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithConnection_PutRequestBody : IAdditionalDataHolder, IBackedModel, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData
        {
            get { return BackingStore.Get<IDictionary<string, object>>("AdditionalData") ?? new Dictionary<string, object>(); }
            set { BackingStore.Set("AdditionalData", value); }
        }
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The public-facing name of the connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName
        {
            get { return BackingStore?.Get<string?>("display_name"); }
            set { BackingStore?.Set("display_name", value); }
        }
#nullable restore
#else
        public string DisplayName
        {
            get { return BackingStore?.Get<string>("display_name"); }
            set { BackingStore?.Set("display_name", value); }
        }
#endif
        /// <summary>Client IDs of applications in which this connection is to be enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EnabledApplications
        {
            get { return BackingStore?.Get<List<string>?>("enabled_applications"); }
            set { BackingStore?.Set("enabled_applications", value); }
        }
#nullable restore
#else
        public List<string> EnabledApplications
        {
            get { return BackingStore?.Get<List<string>>("enabled_applications"); }
            set { BackingStore?.Set("enabled_applications", value); }
        }
#endif
        /// <summary>The internal name of the connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name
        {
            get { return BackingStore?.Get<string?>("name"); }
            set { BackingStore?.Set("name", value); }
        }
#nullable restore
#else
        public string Name
        {
            get { return BackingStore?.Get<string>("name"); }
            set { BackingStore?.Set("name", value); }
        }
#endif
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options? Options
        {
            get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options?>("options"); }
            set { BackingStore?.Set("options", value); }
        }
#nullable restore
#else
        public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options Options
        {
            get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options>("options"); }
            set { BackingStore?.Set("options", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithConnection_PutRequestBody()
        {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "enabled_applications", n => { EnabledApplications = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options>(global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteCollectionOfPrimitiveValues<string>("enabled_applications", EnabledApplications);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options>("options", Options);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1"/>, <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2"/>, <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithConnection_PutRequestBody_options : IBackedModel, IComposedTypeWrapper, IParsable
        {
            /// <summary>Stores model information.</summary>
            public IBackingStore BackingStore { get; private set; }
            /// <summary>Composed type representation for type <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1? WithConnectionPutRequestBodyOptionsMember1
            {
                get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1?>("WithConnection_PutRequestBody_optionsMember1"); }
                set { BackingStore?.Set("WithConnection_PutRequestBody_optionsMember1", value); }
            }
#nullable restore
#else
            public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1 WithConnectionPutRequestBodyOptionsMember1
            {
                get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1>("WithConnection_PutRequestBody_optionsMember1"); }
                set { BackingStore?.Set("WithConnection_PutRequestBody_optionsMember1", value); }
            }
#endif
            /// <summary>Composed type representation for type <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2? WithConnectionPutRequestBodyOptionsMember2
            {
                get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2?>("WithConnection_PutRequestBody_optionsMember2"); }
                set { BackingStore?.Set("WithConnection_PutRequestBody_optionsMember2", value); }
            }
#nullable restore
#else
            public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2 WithConnectionPutRequestBodyOptionsMember2
            {
                get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2>("WithConnection_PutRequestBody_optionsMember2"); }
                set { BackingStore?.Set("WithConnection_PutRequestBody_optionsMember2", value); }
            }
#endif
            /// <summary>Composed type representation for type <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3? WithConnectionPutRequestBodyOptionsMember3
            {
                get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3?>("WithConnection_PutRequestBody_optionsMember3"); }
                set { BackingStore?.Set("WithConnection_PutRequestBody_optionsMember3", value); }
            }
#nullable restore
#else
            public global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3 WithConnectionPutRequestBodyOptionsMember3
            {
                get { return BackingStore?.Get<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3>("WithConnection_PutRequestBody_optionsMember3"); }
                set { BackingStore?.Set("WithConnection_PutRequestBody_optionsMember3", value); }
            }
#endif
            /// <summary>
            /// Instantiates a new <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options"/> and sets the default values.
            /// </summary>
            public WithConnection_PutRequestBody_options()
            {
                BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
            }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody.WithConnection_PutRequestBody_options();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithConnectionPutRequestBodyOptionsMember1 = new global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithConnectionPutRequestBodyOptionsMember2 = new global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithConnectionPutRequestBodyOptionsMember3 = new global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithConnectionPutRequestBodyOptionsMember1 != null)
                {
                    return WithConnectionPutRequestBodyOptionsMember1.GetFieldDeserializers();
                }
                else if(WithConnectionPutRequestBodyOptionsMember2 != null)
                {
                    return WithConnectionPutRequestBodyOptionsMember2.GetFieldDeserializers();
                }
                else if(WithConnectionPutRequestBodyOptionsMember3 != null)
                {
                    return WithConnectionPutRequestBodyOptionsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(WithConnectionPutRequestBodyOptionsMember1 != null)
                {
                    writer.WriteObjectValue<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember1>(null, WithConnectionPutRequestBodyOptionsMember1);
                }
                else if(WithConnectionPutRequestBodyOptionsMember2 != null)
                {
                    writer.WriteObjectValue<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember2>(null, WithConnectionPutRequestBodyOptionsMember2);
                }
                else if(WithConnectionPutRequestBodyOptionsMember3 != null)
                {
                    writer.WriteObjectValue<global::Kinde.Api.Kiota.Management.Api.V1.Connections.Item.WithConnection_PutRequestBody_optionsMember3>(null, WithConnectionPutRequestBodyOptionsMember3);
                }
            }
        }
    }
}
#pragma warning restore CS0618
