// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kinde.Api.Kiota.Management.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Get_billing_agreements_response_agreements_entitlements : IAdditionalDataHolder, IBackedModel, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData
        {
            get { return BackingStore.Get<IDictionary<string, object>>("AdditionalData") ?? new Dictionary<string, object>(); }
            set { BackingStore.Set("AdditionalData", value); }
        }
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The friendly id of an entitlement</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntitlementId
        {
            get { return BackingStore?.Get<string?>("entitlement_id"); }
            set { BackingStore?.Set("entitlement_id", value); }
        }
#nullable restore
#else
        public string EntitlementId
        {
            get { return BackingStore?.Get<string>("entitlement_id"); }
            set { BackingStore?.Set("entitlement_id", value); }
        }
#endif
        /// <summary>The feature code of the feature corresponding to this entitlement</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeatureCode
        {
            get { return BackingStore?.Get<string?>("feature_code"); }
            set { BackingStore?.Set("feature_code", value); }
        }
#nullable restore
#else
        public string FeatureCode
        {
            get { return BackingStore?.Get<string>("feature_code"); }
            set { BackingStore?.Set("feature_code", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kinde.Api.Kiota.Management.Models.Get_billing_agreements_response_agreements_entitlements"/> and sets the default values.
        /// </summary>
        public Get_billing_agreements_response_agreements_entitlements()
        {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kinde.Api.Kiota.Management.Models.Get_billing_agreements_response_agreements_entitlements"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kinde.Api.Kiota.Management.Models.Get_billing_agreements_response_agreements_entitlements CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kinde.Api.Kiota.Management.Models.Get_billing_agreements_response_agreements_entitlements();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entitlement_id", n => { EntitlementId = n.GetStringValue(); } },
                { "feature_code", n => { FeatureCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("entitlement_id", EntitlementId);
            writer.WriteStringValue("feature_code", FeatureCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
