// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kiota.Api.Models
{
    /// <summary>The type of identity to create, e.g. email, username, or phone.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateUser_request_identities_inner_type
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "username")]
        #pragma warning disable CS1591
        Username,
        #pragma warning restore CS1591
    }
}
