// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Get_api_response_api : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The applications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.Get_api_response_api_applications>? Applications { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.Get_api_response_api_applications> Applications { get; set; }
#endif
        /// <summary>A unique identifier for the API - commonly the URL. This value will be used as the `audience` parameter in authorization claims.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Audience { get; set; }
#nullable restore
#else
        public string Audience { get; set; }
#endif
        /// <summary>Unique ID of the API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether or not it is the Kinde management API.</summary>
        public bool? IsManagementApi { get; set; }
        /// <summary>The API&apos;s name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The scopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.Get_api_response_api_scopes>? Scopes { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.Get_api_response_api_scopes> Scopes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.Get_api_response_api"/> and sets the default values.
        /// </summary>
        public Get_api_response_api()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.Get_api_response_api"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.Get_api_response_api CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.Get_api_response_api();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applications", n => { Applications = n.GetCollectionOfObjectValues<global::ApiSdk.Models.Get_api_response_api_applications>(global::ApiSdk.Models.Get_api_response_api_applications.CreateFromDiscriminatorValue)?.AsList(); } },
                { "audience", n => { Audience = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_management_api", n => { IsManagementApi = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfObjectValues<global::ApiSdk.Models.Get_api_response_api_scopes>(global::ApiSdk.Models.Get_api_response_api_scopes.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.Get_api_response_api_applications>("applications", Applications);
            writer.WriteStringValue("audience", Audience);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_management_api", IsManagementApi);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.Get_api_response_api_scopes>("scopes", Scopes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
