// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Kiota.Api.Models
{
    /// <summary>
    /// The billing information if the organization is a billing customer.
    /// </summary>
    public class Get_organization_response_billing : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billing agreements the billing customer is currently subscribed to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Kiota.Api.Models.Get_organization_response_billing_agreements_inner>? Agreements { get; set; }
#nullable restore
#else
        public List<Kiota.Api.Models.Get_organization_response_billing_agreements_inner> Agreements { get; set; }
#endif
        /// <summary>The billing_customer_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingCustomerId { get; set; }
#nullable restore
#else
        public string BillingCustomerId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="Kiota.Api.Models.Get_organization_response_billing"/> and sets the default values.
        /// </summary>
        public Get_organization_response_billing()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Kiota.Api.Models.Get_organization_response_billing"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Kiota.Api.Models.Get_organization_response_billing CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Kiota.Api.Models.Get_organization_response_billing();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agreements", n => { Agreements = n.GetCollectionOfObjectValues<Kiota.Api.Models.Get_organization_response_billing_agreements_inner>(Kiota.Api.Models.Get_organization_response_billing_agreements_inner.CreateFromDiscriminatorValue)?.ToList(); } },
                { "billing_customer_id", n => { BillingCustomerId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<Kiota.Api.Models.Get_organization_response_billing_agreements_inner>("agreements", Agreements);
            writer.WriteStringValue("billing_customer_id", BillingCustomerId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
