/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kinde.Api.Model;
using Kinde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kinde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RemoveOrganizationUsersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemoveOrganizationUsersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemoveOrganizationUsersRequest
        //private RemoveOrganizationUsersRequest instance;

        public RemoveOrganizationUsersRequestTests()
        {
            // TODO uncomment below to create an instance of RemoveOrganizationUsersRequest
            //instance = new RemoveOrganizationUsersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemoveOrganizationUsersRequest
        /// </summary>
        [Fact]
        public void RemoveOrganizationUsersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemoveOrganizationUsersRequest
            //Assert.IsType<RemoveOrganizationUsersRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
