/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kinde.Api.Model;
using Kinde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kinde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateApplicationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateApplicationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateApplicationRequest
        //private UpdateApplicationRequest instance;

        public UpdateApplicationRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateApplicationRequest
            //instance = new UpdateApplicationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateApplicationRequest
        /// </summary>
        [Fact]
        public void UpdateApplicationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateApplicationRequest
            //Assert.IsType<UpdateApplicationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'LanguageKey'
        /// </summary>
        [Fact]
        public void LanguageKeyTest()
        {
            // TODO unit test for the property 'LanguageKey'
        }

        /// <summary>
        /// Test the property 'LogoutUris'
        /// </summary>
        [Fact]
        public void LogoutUrisTest()
        {
            // TODO unit test for the property 'LogoutUris'
        }

        /// <summary>
        /// Test the property 'RedirectUris'
        /// </summary>
        [Fact]
        public void RedirectUrisTest()
        {
            // TODO unit test for the property 'RedirectUris'
        }
    }
}
