/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kinde.Api.Model;
using Kinde.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kinde.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UserProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserProfile
        //private UserProfile instance;

        public UserProfileTests()
        {
            // TODO uncomment below to create an instance of UserProfile
            //instance = new UserProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserProfile
        /// </summary>
        [Fact]
        public void UserProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserProfile
            //Assert.IsType<UserProfile>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PreferredEmail'
        /// </summary>
        [Fact]
        public void PreferredEmailTest()
        {
            // TODO unit test for the property 'PreferredEmail'
        }

        /// <summary>
        /// Test the property 'ProvidedId'
        /// </summary>
        [Fact]
        public void ProvidedIdTest()
        {
            // TODO unit test for the property 'ProvidedId'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Fact]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }
    }
}
