// <auto-generated/>
#pragma warning disable CS0618
using Kinde.Api.Kiota.Management.Api.V1.Api_keys;
using Kinde.Api.Kiota.Management.Api.V1.Apis;
using Kinde.Api.Kiota.Management.Api.V1.Applications;
using Kinde.Api.Kiota.Management.Api.V1.Billing;
using Kinde.Api.Kiota.Management.Api.V1.Business;
using Kinde.Api.Kiota.Management.Api.V1.Connected_apps;
using Kinde.Api.Kiota.Management.Api.V1.Connections;
using Kinde.Api.Kiota.Management.Api.V1.EnvironmentNamespace;
using Kinde.Api.Kiota.Management.Api.V1.Environment_variables;
using Kinde.Api.Kiota.Management.Api.V1.Event_types;
using Kinde.Api.Kiota.Management.Api.V1.Events;
using Kinde.Api.Kiota.Management.Api.V1.Feature_flags;
using Kinde.Api.Kiota.Management.Api.V1.Identities;
using Kinde.Api.Kiota.Management.Api.V1.Industries;
using Kinde.Api.Kiota.Management.Api.V1.Mfa;
using Kinde.Api.Kiota.Management.Api.V1.Organization;
using Kinde.Api.Kiota.Management.Api.V1.Organizations;
using Kinde.Api.Kiota.Management.Api.V1.Permissions;
using Kinde.Api.Kiota.Management.Api.V1.Properties;
using Kinde.Api.Kiota.Management.Api.V1.Property_categories;
using Kinde.Api.Kiota.Management.Api.V1.Roles;
using Kinde.Api.Kiota.Management.Api.V1.Search;
using Kinde.Api.Kiota.Management.Api.V1.Subscribers;
using Kinde.Api.Kiota.Management.Api.V1.Timezones;
using Kinde.Api.Kiota.Management.Api.V1.User;
using Kinde.Api.Kiota.Management.Api.V1.Users;
using Kinde.Api.Kiota.Management.Api.V1.Webhooks;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kinde.Api.Kiota.Management.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The api_keys property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Api_keys.Api_keysRequestBuilder Api_keys
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Api_keys.Api_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apis property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Apis.ApisRequestBuilder Apis
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Apis.ApisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The applications property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The billing property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Billing.BillingRequestBuilder Billing
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Billing.BillingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The business property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Business.BusinessRequestBuilder Business
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Business.BusinessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The connected_apps property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Connected_apps.Connected_appsRequestBuilder Connected_apps
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Connected_apps.Connected_appsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The connections property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Connections.ConnectionsRequestBuilder Connections
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Connections.ConnectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The environment property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.EnvironmentNamespace.EnvironmentRequestBuilder Environment
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.EnvironmentNamespace.EnvironmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The environment_variables property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Environment_variables.Environment_variablesRequestBuilder Environment_variables
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Environment_variables.Environment_variablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The event_types property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Event_types.Event_typesRequestBuilder Event_types
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Event_types.Event_typesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Events.EventsRequestBuilder Events
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The feature_flags property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Feature_flags.Feature_flagsRequestBuilder Feature_flags
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Feature_flags.Feature_flagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The identities property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Identities.IdentitiesRequestBuilder Identities
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Identities.IdentitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The industries property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Industries.IndustriesRequestBuilder Industries
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Industries.IndustriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mfa property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Mfa.MfaRequestBuilder Mfa
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Mfa.MfaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organization property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Organization.OrganizationRequestBuilder Organization
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Organization.OrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The properties property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The property_categories property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Property_categories.Property_categoriesRequestBuilder Property_categories
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Property_categories.Property_categoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Roles.RolesRequestBuilder Roles
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Search.SearchRequestBuilder Search
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscribers property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Subscribers.SubscribersRequestBuilder Subscribers
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Subscribers.SubscribersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timezones property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Timezones.TimezonesRequestBuilder Timezones
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Timezones.TimezonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.User.UserRequestBuilder User
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Users.UsersRequestBuilder Users
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Kinde.Api.Kiota.Management.Api.V1.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Kinde.Api.Kiota.Management.Api.V1.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kinde.Api.Kiota.Management.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kinde.Api.Kiota.Management.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
