// <auto-generated>
/*
 * Kinde Management API
 *
 *  Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Kinde.Api.Client;

namespace Kinde.Api.Model
{
    /// <summary>
    /// AuthorizeAppApiResponse
    /// </summary>
    public partial class AuthorizeAppApiResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizeAppApiResponse" /> class.
        /// </summary>
        /// <param name="message">message</param>
        /// <param name="code">code</param>
        /// <param name="applicationsDisconnected">applicationsDisconnected</param>
        /// <param name="applicationsConnected">applicationsConnected</param>
        [JsonConstructor]
        public AuthorizeAppApiResponse(Option<string?> message = default, Option<string?> code = default, Option<List<string>?> applicationsDisconnected = default, Option<List<string>?> applicationsConnected = default)
        {
            MessageOption = message;
            CodeOption = code;
            ApplicationsDisconnectedOption = applicationsDisconnected;
            ApplicationsConnectedOption = applicationsConnected;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /* <example>API applications updated</example> */
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        /* <example>API_APPLICATIONS_UPDATED</example> */
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption; } set { this.CodeOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ApplicationsDisconnected
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ApplicationsDisconnectedOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplicationsDisconnected
        /// </summary>
        [JsonPropertyName("applications_disconnected")]
        public List<string>? ApplicationsDisconnected { get { return this.ApplicationsDisconnectedOption; } set { this.ApplicationsDisconnectedOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Used to track the state of ApplicationsConnected
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ApplicationsConnectedOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplicationsConnected
        /// </summary>
        [JsonPropertyName("applications_connected")]
        public List<string>? ApplicationsConnected { get { return this.ApplicationsConnectedOption; } set { this.ApplicationsConnectedOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthorizeAppApiResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  ApplicationsDisconnected: ").Append(ApplicationsDisconnected).Append("\n");
            sb.Append("  ApplicationsConnected: ").Append(ApplicationsConnected).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuthorizeAppApiResponse" />
    /// </summary>
    public class AuthorizeAppApiResponseJsonConverter : JsonConverter<AuthorizeAppApiResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="AuthorizeAppApiResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuthorizeAppApiResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> message = default;
            Option<string?> code = default;
            Option<List<string>?> applicationsDisconnected = default;
            Option<List<string>?> applicationsConnected = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "applications_disconnected":
                            applicationsDisconnected = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "applications_connected":
                            applicationsConnected = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class AuthorizeAppApiResponse.");

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class AuthorizeAppApiResponse.");

            if (applicationsDisconnected.IsSet && applicationsDisconnected.Value == null)
                throw new ArgumentNullException(nameof(applicationsDisconnected), "Property is not nullable for class AuthorizeAppApiResponse.");

            if (applicationsConnected.IsSet && applicationsConnected.Value == null)
                throw new ArgumentNullException(nameof(applicationsConnected), "Property is not nullable for class AuthorizeAppApiResponse.");

            return new AuthorizeAppApiResponse(message, code, applicationsDisconnected, applicationsConnected);
        }

        /// <summary>
        /// Serializes a <see cref="AuthorizeAppApiResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authorizeAppApiResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuthorizeAppApiResponse authorizeAppApiResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, authorizeAppApiResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuthorizeAppApiResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authorizeAppApiResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuthorizeAppApiResponse authorizeAppApiResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (authorizeAppApiResponse.MessageOption.IsSet && authorizeAppApiResponse.Message == null)
                throw new ArgumentNullException(nameof(authorizeAppApiResponse.Message), "Property is required for class AuthorizeAppApiResponse.");

            if (authorizeAppApiResponse.CodeOption.IsSet && authorizeAppApiResponse.Code == null)
                throw new ArgumentNullException(nameof(authorizeAppApiResponse.Code), "Property is required for class AuthorizeAppApiResponse.");

            if (authorizeAppApiResponse.ApplicationsDisconnectedOption.IsSet && authorizeAppApiResponse.ApplicationsDisconnected == null)
                throw new ArgumentNullException(nameof(authorizeAppApiResponse.ApplicationsDisconnected), "Property is required for class AuthorizeAppApiResponse.");

            if (authorizeAppApiResponse.ApplicationsConnectedOption.IsSet && authorizeAppApiResponse.ApplicationsConnected == null)
                throw new ArgumentNullException(nameof(authorizeAppApiResponse.ApplicationsConnected), "Property is required for class AuthorizeAppApiResponse.");

            if (authorizeAppApiResponse.MessageOption.IsSet)
                writer.WriteString("message", authorizeAppApiResponse.Message);

            if (authorizeAppApiResponse.CodeOption.IsSet)
                writer.WriteString("code", authorizeAppApiResponse.Code);

            if (authorizeAppApiResponse.ApplicationsDisconnectedOption.IsSet)
            {
                writer.WritePropertyName("applications_disconnected");
                JsonSerializer.Serialize(writer, authorizeAppApiResponse.ApplicationsDisconnected, jsonSerializerOptions);
            }
            if (authorizeAppApiResponse.ApplicationsConnectedOption.IsSet)
            {
                writer.WritePropertyName("applications_connected");
                JsonSerializer.Serialize(writer, authorizeAppApiResponse.ApplicationsConnected, jsonSerializerOptions);
            }
        }
    }
}
