// <auto-generated>
/*
 * Kinde Management API
 *
 *  Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Kinde.Api.Client;

namespace Kinde.Api.Model
{
    /// <summary>
    /// </summary>
    public partial class CreateOrganizationResponse
    {
        /// <summary>
        /// </summary>
        /// <param name="message">Response message.</param>
        /// <param name="code">Response code.</param>
        /// <param name="organization">organization</param>
        [JsonConstructor]
        public CreateOrganizationResponse(Option<string?> message = default, Option<string?> code = default, Option<CreateOrganizationResponseOrganization?> organization = default)
        {
            MessageOption = message;
            CodeOption = code;
            OrganizationOption = organization;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Response message.
        /// </summary>
        /// <value>Response message.</value>
        /* <example>Success</example> */
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// Response code.
        /// </summary>
        /// <value>Response code.</value>
        /* <example>OK</example> */
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CreateOrganizationResponseOrganization?> OrganizationOption { get; private set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("organization")]
        public CreateOrganizationResponseOrganization? Organization { get { return this.OrganizationOption; } set { this.OrganizationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOrganizationResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Organization: ").Append(Organization).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// </summary>
    public class CreateOrganizationResponseJsonConverter : JsonConverter<CreateOrganizationResponse>
    {
        /// <summary>
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateOrganizationResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> message = default;
            Option<string?> code = default;
            Option<CreateOrganizationResponseOrganization?> organization = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organization":
                            organization = new Option<CreateOrganizationResponseOrganization?>(JsonSerializer.Deserialize<CreateOrganizationResponseOrganization>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class CreateOrganizationResponse.");

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class CreateOrganizationResponse.");

            if (organization.IsSet && organization.Value == null)
                throw new ArgumentNullException(nameof(organization), "Property is not nullable for class CreateOrganizationResponse.");

            return new CreateOrganizationResponse(message, code, organization);
        }

        /// <summary>
        /// </summary>
        /// <param name="writer"></param>
        public override void Write(Utf8JsonWriter writer, CreateOrganizationResponse createOrganizationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createOrganizationResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// </summary>
        /// <param name="writer"></param>
        public void WriteProperties(Utf8JsonWriter writer, CreateOrganizationResponse createOrganizationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createOrganizationResponse.MessageOption.IsSet && createOrganizationResponse.Message == null)
                throw new ArgumentNullException(nameof(createOrganizationResponse.Message), "Property is required for class CreateOrganizationResponse.");

            if (createOrganizationResponse.CodeOption.IsSet && createOrganizationResponse.Code == null)
                throw new ArgumentNullException(nameof(createOrganizationResponse.Code), "Property is required for class CreateOrganizationResponse.");

            if (createOrganizationResponse.OrganizationOption.IsSet && createOrganizationResponse.Organization == null)
                throw new ArgumentNullException(nameof(createOrganizationResponse.Organization), "Property is required for class CreateOrganizationResponse.");

            if (createOrganizationResponse.MessageOption.IsSet)
                writer.WriteString("message", createOrganizationResponse.Message);

            if (createOrganizationResponse.CodeOption.IsSet)
                writer.WriteString("code", createOrganizationResponse.Code);

            if (createOrganizationResponse.OrganizationOption.IsSet)
            {
                writer.WritePropertyName("organization");
                JsonSerializer.Serialize(writer, createOrganizationResponse.Organization, jsonSerializerOptions);
            }
        }
    }
}
