/*
 * Kinde Management API
 *
 *  Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Kinde.Api.Client.OpenAPIDateConverter;

namespace Kinde.Api.Model
{
    /// <summary>
    /// CreateOrganizationUserPermissionRequest
    /// </summary>
    [DataContract(Name = "CreateOrganizationUserPermission_request")]
    public partial class CreateOrganizationUserPermissionRequest : IEquatable<CreateOrganizationUserPermissionRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrganizationUserPermissionRequest" /> class.
        /// </summary>
        /// <param name="permissionId">The permission id..</param>
        public CreateOrganizationUserPermissionRequest(string permissionId = default(string))
        {
            this.PermissionId = permissionId;
        }

        /// <summary>
        /// The permission id.
        /// </summary>
        /// <value>The permission id.</value>
        [DataMember(Name = "permission_id", EmitDefaultValue = false)]
        public string PermissionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOrganizationUserPermissionRequest {\n");
            sb.Append("  PermissionId: ").Append(PermissionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateOrganizationUserPermissionRequest);
        }

        /// <summary>
        /// Returns true if CreateOrganizationUserPermissionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateOrganizationUserPermissionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateOrganizationUserPermissionRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PermissionId == input.PermissionId ||
                    (this.PermissionId != null &&
                    this.PermissionId.Equals(input.PermissionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PermissionId != null)
                {
                    hashCode = (hashCode * 59) + this.PermissionId.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
