// <auto-generated>
/*
 * Kinde Management API
 *
 *  Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Kinde.Api.Client;

namespace Kinde.Api.Model
{
    /// <summary>
    /// </summary>
    public partial class GetOrganizationsUserPermissionsResponse
    {
        /// <summary>
        /// </summary>
        /// <param name="code">Response code.</param>
        /// <param name="message">Response message.</param>
        /// <param name="permissions">permissions</param>
        [JsonConstructor]
        public GetOrganizationsUserPermissionsResponse(Option<string?> code = default, Option<string?> message = default, Option<List<OrganizationUserPermission>?> permissions = default)
        {
            CodeOption = code;
            MessageOption = message;
            PermissionsOption = permissions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// Response code.
        /// </summary>
        /// <value>Response code.</value>
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Response message.
        /// </summary>
        /// <value>Response message.</value>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<OrganizationUserPermission>?> PermissionsOption { get; private set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("permissions")]
        public List<OrganizationUserPermission>? Permissions { get { return this.PermissionsOption; } set { this.PermissionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetOrganizationsUserPermissionsResponse {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// </summary>
    public class GetOrganizationsUserPermissionsResponseJsonConverter : JsonConverter<GetOrganizationsUserPermissionsResponse>
    {
        /// <summary>
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetOrganizationsUserPermissionsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<string?> message = default;
            Option<List<OrganizationUserPermission>?> permissions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "permissions":
                            permissions = new Option<List<OrganizationUserPermission>?>(JsonSerializer.Deserialize<List<OrganizationUserPermission>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class GetOrganizationsUserPermissionsResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class GetOrganizationsUserPermissionsResponse.");

            if (permissions.IsSet && permissions.Value == null)
                throw new ArgumentNullException(nameof(permissions), "Property is not nullable for class GetOrganizationsUserPermissionsResponse.");

            return new GetOrganizationsUserPermissionsResponse(code, message, permissions);
        }

        /// <summary>
        /// </summary>
        /// <param name="writer"></param>
        public override void Write(Utf8JsonWriter writer, GetOrganizationsUserPermissionsResponse getOrganizationsUserPermissionsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getOrganizationsUserPermissionsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// </summary>
        /// <param name="writer"></param>
        public void WriteProperties(Utf8JsonWriter writer, GetOrganizationsUserPermissionsResponse getOrganizationsUserPermissionsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getOrganizationsUserPermissionsResponse.CodeOption.IsSet && getOrganizationsUserPermissionsResponse.Code == null)
                throw new ArgumentNullException(nameof(getOrganizationsUserPermissionsResponse.Code), "Property is required for class GetOrganizationsUserPermissionsResponse.");

            if (getOrganizationsUserPermissionsResponse.MessageOption.IsSet && getOrganizationsUserPermissionsResponse.Message == null)
                throw new ArgumentNullException(nameof(getOrganizationsUserPermissionsResponse.Message), "Property is required for class GetOrganizationsUserPermissionsResponse.");

            if (getOrganizationsUserPermissionsResponse.PermissionsOption.IsSet && getOrganizationsUserPermissionsResponse.Permissions == null)
                throw new ArgumentNullException(nameof(getOrganizationsUserPermissionsResponse.Permissions), "Property is required for class GetOrganizationsUserPermissionsResponse.");

            if (getOrganizationsUserPermissionsResponse.CodeOption.IsSet)
                writer.WriteString("code", getOrganizationsUserPermissionsResponse.Code);

            if (getOrganizationsUserPermissionsResponse.MessageOption.IsSet)
                writer.WriteString("message", getOrganizationsUserPermissionsResponse.Message);

            if (getOrganizationsUserPermissionsResponse.PermissionsOption.IsSet)
            {
                writer.WritePropertyName("permissions");
                JsonSerializer.Serialize(writer, getOrganizationsUserPermissionsResponse.Permissions, jsonSerializerOptions);
            }
        }
    }
}
