// <auto-generated/>
using Kiota.Api.Api.V1.Apis.Item;
using Kiota.Api.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kiota.Api.Api.V1.Apis
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\apis
    /// </summary>
    public class ApisRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kiota.Api.api.v1.apis.item collection</summary>
        /// <param name="position">The API&apos;s ID.</param>
        /// <returns>A <see cref="Kiota.Api.Api.V1.Apis.Item.WithApi_ItemRequestBuilder"/></returns>
        public Kiota.Api.Api.V1.Apis.Item.WithApi_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("api_id", position);
                return new Kiota.Api.Api.V1.Apis.Item.WithApi_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="Kiota.Api.Api.V1.Apis.ApisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApisRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/apis{?expand*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="Kiota.Api.Api.V1.Apis.ApisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApisRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/apis{?expand*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of your APIs. The APIs are returned sorted by name.&lt;div&gt;  &lt;code&gt;read:apis&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="Kiota.Api.Models.Get_apis_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 400 status code</exception>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 403 status code</exception>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Kiota.Api.Models.Get_apis_response?> GetAsync(Action<RequestConfiguration<Kiota.Api.Api.V1.Apis.ApisRequestBuilder.ApisRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Kiota.Api.Models.Get_apis_response> GetAsync(Action<RequestConfiguration<Kiota.Api.Api.V1.Apis.ApisRequestBuilder.ApisRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
                { "403", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
                { "429", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<Kiota.Api.Models.Get_apis_response>(requestInfo, Kiota.Api.Models.Get_apis_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Register a new API. For more information read [Register and manage APIs](https://docs.kinde.com/developer-tools/your-apis/register-manage-apis/).&lt;div&gt;  &lt;code&gt;create:apis&lt;/code&gt;&lt;/div&gt;
        /// Register and manage APIs <see href="https://docs.kinde.com/developer-tools/your-apis/register-manage-apis" />
        /// </summary>
        /// <returns>A <see cref="Kiota.Api.Models.Create_apis_response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 400 status code</exception>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 403 status code</exception>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Kiota.Api.Models.Create_apis_response?> PostAsync(Kiota.Api.Models.AddAPIs_request body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Kiota.Api.Models.Create_apis_response> PostAsync(Kiota.Api.Models.AddAPIs_request body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
                { "403", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
                { "429", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<Kiota.Api.Models.Create_apis_response>(requestInfo, Kiota.Api.Models.Create_apis_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of your APIs. The APIs are returned sorted by name.&lt;div&gt;  &lt;code&gt;read:apis&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<Kiota.Api.Api.V1.Apis.ApisRequestBuilder.ApisRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<Kiota.Api.Api.V1.Apis.ApisRequestBuilder.ApisRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Register a new API. For more information read [Register and manage APIs](https://docs.kinde.com/developer-tools/your-apis/register-manage-apis/).&lt;div&gt;  &lt;code&gt;create:apis&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Kiota.Api.Models.AddAPIs_request body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Kiota.Api.Models.AddAPIs_request body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="Kiota.Api.Api.V1.Apis.ApisRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public Kiota.Api.Api.V1.Apis.ApisRequestBuilder WithUrl(string rawUrl)
        {
            return new Kiota.Api.Api.V1.Apis.ApisRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of your APIs. The APIs are returned sorted by name.&lt;div&gt;  &lt;code&gt;read:apis&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        public class ApisRequestBuilderGetQueryParameters 
        {
            /// <summary>Specify additional data to retrieve. Use &quot;scopes&quot;.</summary>
            [Obsolete("This property is deprecated, use ExpandAsGetExpandQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public string? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public string Expand { get; set; }
#endif
            /// <summary>Specify additional data to retrieve. Use &quot;scopes&quot;.</summary>
            [QueryParameter("expand")]
            public Kiota.Api.Api.V1.Apis.GetExpandQueryParameterType? ExpandAsGetExpandQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ApisRequestBuilderGetRequestConfiguration : RequestConfiguration<Kiota.Api.Api.V1.Apis.ApisRequestBuilder.ApisRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ApisRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
