/*
 * Kinde Accounts API
 *
 * API for querying the current user's permissions, roles, entitlements, and feature flags
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kinde.Accounts.Model;
using Kinde.Accounts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kinde.Accounts.Test.Model
{
    /// <summary>
    ///  Class for testing UserProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserProfile
        //private UserProfile instance;

        public UserProfileTests()
        {
            // TODO uncomment below to create an instance of UserProfile
            //instance = new UserProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserProfile
        /// </summary>
        [Fact]
        public void UserProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserProfile
            //Assert.IsType<UserProfile>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'GivenName'
        /// </summary>
        [Fact]
        public void GivenNameTest()
        {
            // TODO unit test for the property 'GivenName'
        }

        /// <summary>
        /// Test the property 'FamilyName'
        /// </summary>
        [Fact]
        public void FamilyNameTest()
        {
            // TODO unit test for the property 'FamilyName'
        }

        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Fact]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }
    }
}
