// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Api.V1.Roles.Item.Permissions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PermissionsPatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Permissions to add or remove from the role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody_permissions>? Permissions { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody_permissions> Permissions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody"/> and sets the default values.
        /// </summary>
        public PermissionsPatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "permissions", n => { Permissions = n.GetCollectionOfObjectValues<global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody_permissions>(global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody_permissions.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Api.V1.Roles.Item.Permissions.PermissionsPatchRequestBody_permissions>("permissions", Permissions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
