// <auto-generated/>
using Kiota.Api.Api.V1.Roles.Item.Permissions.Item;
using Kiota.Api.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kiota.Api.Api.V1.Roles.Item.Permissions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\roles\{role_id}\permissions
    /// </summary>
    public class PermissionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kiota.Api.api.v1.roles.item.permissions.item collection</summary>
        /// <param name="position">The permission&apos;s public id.</param>
        /// <returns>A <see cref="Kiota.Api.Api.V1.Roles.Item.Permissions.Item.WithPermission_ItemRequestBuilder"/></returns>
        public Kiota.Api.Api.V1.Roles.Item.Permissions.Item.WithPermission_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("permission_id", position);
                return new Kiota.Api.Api.V1.Roles.Item.Permissions.Item.WithPermission_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PermissionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/roles/{role_id}/permissions{?next_token*,page_size*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PermissionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/roles/{role_id}/permissions{?next_token*,page_size*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Get permissions for a role.&lt;div&gt;  &lt;code&gt;read:role_permissions&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="Kiota.Api.Models.Role_permissions_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Kiota.Api.Models.Role_permissions_response?> GetAsync(Action<RequestConfiguration<Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder.PermissionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Kiota.Api.Models.Role_permissions_response> GetAsync(Action<RequestConfiguration<Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder.PermissionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<Kiota.Api.Models.Role_permissions_response>(requestInfo, Kiota.Api.Models.Role_permissions_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update role permissions.&lt;div&gt;  &lt;code&gt;update:role_permissions&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="Kiota.Api.Models.Update_role_permissions_response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Kiota.Api.Models.Error_response">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Kiota.Api.Models.Update_role_permissions_response?> PatchAsync(Kiota.Api.Models.UpdateRolePermissions_request body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Kiota.Api.Models.Update_role_permissions_response> PatchAsync(Kiota.Api.Models.UpdateRolePermissions_request body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", Kiota.Api.Models.Error_response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<Kiota.Api.Models.Update_role_permissions_response>(requestInfo, Kiota.Api.Models.Update_role_permissions_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get permissions for a role.&lt;div&gt;  &lt;code&gt;read:role_permissions&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder.PermissionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder.PermissionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;charset=utf-8");
            return requestInfo;
        }
        /// <summary>
        /// Update role permissions.&lt;div&gt;  &lt;code&gt;update:role_permissions&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(Kiota.Api.Models.UpdateRolePermissions_request body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(Kiota.Api.Models.UpdateRolePermissions_request body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;charset=utf-8");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder WithUrl(string rawUrl)
        {
            return new Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get permissions for a role.&lt;div&gt;  &lt;code&gt;read:role_permissions&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        public class PermissionsRequestBuilderGetQueryParameters 
        {
            /// <summary>A string to get the next page of results if there are more results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("next_token")]
            public string? NextToken { get; set; }
#nullable restore
#else
            [QueryParameter("next_token")]
            public string NextToken { get; set; }
#endif
            /// <summary>Number of results per page. Defaults to 10 if parameter not sent.</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>Field and order to sort the result by.</summary>
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>Field and order to sort the result by.</summary>
            [QueryParameter("sort")]
            public Kiota.Api.Api.V1.Roles.Item.Permissions.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class PermissionsRequestBuilderGetRequestConfiguration : RequestConfiguration<Kiota.Api.Api.V1.Roles.Item.Permissions.PermissionsRequestBuilder.PermissionsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class PermissionsRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
