// <auto-generated/>
#pragma warning disable CS0618
using Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.Item;
using Kinde.Api.Kiota.Management.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\users\{user_id}\properties
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PropertiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kinde.Api.Kiota.Management.api.v1.users.item.properties.item collection</summary>
        /// <param name="position">The identifier for the property</param>
        /// <returns>A <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.Item.WithProperty_keyItemRequestBuilder"/></returns>
        public global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.Item.WithProperty_keyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("property_key", position);
                return new global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.Item.WithProperty_keyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/users/{user_id}/properties", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/users/{user_id}/properties", rawUrl)
        {
        }
        /// <summary>
        /// Gets properties for an user by ID.&lt;div&gt;  &lt;code&gt;read:user_properties&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="global::Kinde.Api.Kiota.Management.Models.Get_property_values_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kinde.Api.Kiota.Management.Models.Error_response">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kinde.Api.Kiota.Management.Models.Get_property_values_response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kinde.Api.Kiota.Management.Models.Get_property_values_response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kinde.Api.Kiota.Management.Models.Error_response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kinde.Api.Kiota.Management.Models.Get_property_values_response>(requestInfo, global::Kinde.Api.Kiota.Management.Models.Get_property_values_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update property values.&lt;div&gt;  &lt;code&gt;update:user_properties&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="global::Kinde.Api.Kiota.Management.Models.Success_response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kinde.Api.Kiota.Management.Models.Error_response">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kinde.Api.Kiota.Management.Models.Success_response?> PatchAsync(global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kinde.Api.Kiota.Management.Models.Success_response> PatchAsync(global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kinde.Api.Kiota.Management.Models.Error_response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kinde.Api.Kiota.Management.Models.Success_response>(requestInfo, global::Kinde.Api.Kiota.Management.Models.Success_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets properties for an user by ID.&lt;div&gt;  &lt;code&gt;read:user_properties&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;charset=utf-8");
            return requestInfo;
        }
        /// <summary>
        /// Update property values.&lt;div&gt;  &lt;code&gt;update:user_properties&lt;/code&gt;&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;charset=utf-8");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kinde.Api.Kiota.Management.Api.V1.Users.Item.Properties.PropertiesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
